name: Create Release

on:
  push:
    branches:
      - main
      - master

jobs:
  create-release:
    with:
      sonar: false
    uses: liquibase/build-logic/.github/workflows/create-release.yml@main
    secrets: inherit
