name: Release Extension to Sonatype

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@allow-defining-java-build-version
    secrets: inherit
    with:
      javaBuildVersion: 8
