name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  #delete this block if the repository you are creating is a PRO extension
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@DEVX-12
    secrets: inherit
    with:
      java: '[8]'
      javaBuildVersion: '8'
      skipSonar: true
